run:
  concurrency: 4
  timeout: 30m
  issues-exit-code: 1
  tests: true
  build-tags: []
  skip-dirs: []
  skip-dirs-use-default: true
  skip-files: []
  modules-download-mode: readonly
  allow-parallel-runners: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  gocritic:
    enabled-tags:
      - performance
  gosimple:
    checks: [ "all" ]
  govet:
    enable:
      - atomicalign
      - shadow
  staticcheck:
    checks: [ "all" ]
  unparam:
    check-exported: true
linters:
  disable-all: false
  enable:
    - errcheck
    - gocognit
    - gocritic
    - gofumpt
    - goimports
    - gosimple
    - govet
    - megacheck
    - nestif
    - staticcheck
    - stylecheck
    - unparam
    - unused
  fast: false


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - lll
      source: "^//go:generate "
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
