// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	postmark "github.com/mattevans/postmark-go"
	mock "github.com/stretchr/testify/mock"
)

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *EmailSender) Send(_a0 *postmark.Email) (*postmark.EmailResponse, *postmark.Response, error) {
	ret := _m.Called(_a0)

	var r0 *postmark.EmailResponse
	if rf, ok := ret.Get(0).(func(*postmark.Email) *postmark.EmailResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postmark.EmailResponse)
		}
	}

	var r1 *postmark.Response
	if rf, ok := ret.Get(1).(func(*postmark.Email) *postmark.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*postmark.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*postmark.Email) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
