// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	config "gitlab.com/etke.cc/buscarron/config"
	common "gitlab.com/etke.cc/buscarron/sub/ext/common"

	context "context"

	mautrix "maunium.net/go/mautrix"

	mock "github.com/stretchr/testify/mock"
)

// Extension is an autogenerated mock type for the Extension type
type Extension struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Extension) Execute(_a0 context.Context, _a1 common.Validator, _a2 *config.Form, _a3 map[string]string) (string, []*mautrix.ReqUploadMedia) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 []*mautrix.ReqUploadMedia
	if rf, ok := ret.Get(0).(func(context.Context, common.Validator, *config.Form, map[string]string) (string, []*mautrix.ReqUploadMedia)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Validator, *config.Form, map[string]string) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Validator, *config.Form, map[string]string) []*mautrix.ReqUploadMedia); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*mautrix.ReqUploadMedia)
		}
	}

	return r0, r1
}

// Validate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Extension) Validate(_a0 context.Context, _a1 common.Validator, _a2 *config.Form, _a3 map[string]string) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Validator, *config.Form, map[string]string) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExtension creates a new instance of Extension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExtension(t interface {
	mock.TestingT
	Cleanup(func())
}) *Extension {
	mock := &Extension{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
