// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	config "gitlab.com/etke.cc/buscarron/config"

	mautrix "maunium.net/go/mautrix"

	mock "github.com/stretchr/testify/mock"
)

// Extension is an autogenerated mock type for the Extension type
type Extension struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *Extension) Execute(_a0 *config.Form, _a1 map[string]string) (string, []*mautrix.ReqUploadMedia) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(*config.Form, map[string]string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 []*mautrix.ReqUploadMedia
	if rf, ok := ret.Get(1).(func(*config.Form, map[string]string) []*mautrix.ReqUploadMedia); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*mautrix.ReqUploadMedia)
		}
	}

	return r0, r1
}
