// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NetworkValidator is an autogenerated mock type for the NetworkValidator type
type NetworkValidator struct {
	mock.Mock
}

// A provides a mock function with given fields: host
func (_m *NetworkValidator) A(host string) bool {
	ret := _m.Called(host)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CNAME provides a mock function with given fields: host
func (_m *NetworkValidator) CNAME(host string) bool {
	ret := _m.Called(host)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetBase provides a mock function with given fields: domain
func (_m *NetworkValidator) GetBase(domain string) string {
	ret := _m.Called(domain)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
