// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mautrix "maunium.net/go/mautrix"
	id "maunium.net/go/mautrix/id"

	mock "github.com/stretchr/testify/mock"
)

// Sender is an autogenerated mock type for the Sender type
type Sender struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *Sender) Send(_a0 id.RoomID, _a1 string) {
	_m.Called(_a0, _a1)
}

// SendFile provides a mock function with given fields: _a0, _a1
func (_m *Sender) SendFile(_a0 id.RoomID, _a1 *mautrix.ReqUploadMedia) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewSender creates a new instance of Sender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSender(t mockConstructorTestingTNewSender) *Sender {
	mock := &Sender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
