// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	context "context"

	event "maunium.net/go/mautrix/event"

	id "maunium.net/go/mautrix/id"

	mock "github.com/stretchr/testify/mock"
)

// senderByEmail is an autogenerated mock type for the senderByEmail type
type senderByEmail struct {
	mock.Mock
}

// FindEventBy provides a mock function with given fields: ctx, roomID, field, value, fromToken
func (_m *senderByEmail) FindEventBy(ctx context.Context, roomID id.RoomID, field string, value string, fromToken ...string) *event.Event {
	_va := make([]interface{}, len(fromToken))
	for _i := range fromToken {
		_va[_i] = fromToken[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, roomID, field, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindEventBy")
	}

	var r0 *event.Event
	if rf, ok := ret.Get(0).(func(context.Context, id.RoomID, string, string, ...string) *event.Event); ok {
		r0 = rf(ctx, roomID, field, value, fromToken...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.Event)
		}
	}

	return r0
}

// Send provides a mock function with given fields: ctx, roomID, message, attributes
func (_m *senderByEmail) Send(ctx context.Context, roomID id.RoomID, message string, attributes map[string]interface{}) id.EventID {
	ret := _m.Called(ctx, roomID, message, attributes)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 id.EventID
	if rf, ok := ret.Get(0).(func(context.Context, id.RoomID, string, map[string]interface{}) id.EventID); ok {
		r0 = rf(ctx, roomID, message, attributes)
	} else {
		r0 = ret.Get(0).(id.EventID)
	}

	return r0
}

// SendByEmail provides a mock function with given fields: ctx, roomID, email, message, reactions
func (_m *senderByEmail) SendByEmail(ctx context.Context, roomID id.RoomID, email string, message string, reactions ...string) map[string]interface{} {
	_va := make([]interface{}, len(reactions))
	for _i := range reactions {
		_va[_i] = reactions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, roomID, email, message)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendByEmail")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context, id.RoomID, string, string, ...string) map[string]interface{}); ok {
		r0 = rf(ctx, roomID, email, message, reactions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// newSenderByEmail creates a new instance of senderByEmail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSenderByEmail(t interface {
	mock.TestingT
	Cleanup(func())
}) *senderByEmail {
	mock := &senderByEmail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
